Feature/123 2.3 my diary presentation
INtouch-YP/intouch-android pull request #126
Opened 2024-07-01 11:26 UTC by nim0y

Several changes in UiKit CustomTopBar, NoteCard
Change in AppNavHost add an onBackButtonClick
Add presentation layer for diary.

2024-07-02 15:41 UTC, JudjinGM reviewed
Посмотри, пожалуйста ПР https://github.com/INtouch-YP/intouch-android/pull/127, у вас очень похожие задачи, там правильно реализован показ диалогов, хранение и обработка стейта итд, также надо будет как там добавить loading при загрузке данных, обновление стейта через update{} итд

2024-07-04 12:44 UTC, smitford requested changes

2024-07-04 12:44 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +            ConfirmDeleteDialog(
Поехал текст кнопки подтверждения

2024-07-04 12:44 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/CreatingNoteIntroductionScreen.kt
> +                .padding(top = 48.dp),
![Screenshot_20240704_163040_care intouch app debug](https://github.com/INtouch-YP/intouch-android/assets/17237585/5b00be65-6f55-4d11-b04e-55185f1448ff)

2024-07-04 12:44 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +        DiaryHeader(
![Screenshot_20240704_161725_care intouch app debug](https://github.com/INtouch-YP/intouch-android/assets/17237585/f17586d5-481f-47ab-aa6e-2ca33ebe2c8d)

2024-07-04 12:44 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +            ConfirmDeleteDialog(
![Screenshot_20240704_161642_care intouch app debug](https://github.com/INtouch-YP/intouch-android/assets/17237585/7d03be70-d65c-48e5-b383-6a3ee7e2dc1e)

2024-07-04 12:58 UTC, smitford requested changes

2024-07-04 12:58 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +
удалить строку

2024-07-04 12:58 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +    val popUp: SharedFlow<DiaryPopUp> = _popUp.asSharedFlow()
это sideeffect? он не обязательно pop up

2024-07-04 12:58 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/CreatingNoteIntroductionScreen.kt
> +            CustomTopBar(
не подизайну, так же пропал текст кнопки

2024-07-04 12:58 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +        DiaryHeader(
не по дизайну

2024-07-04 12:58 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +                onConfirm = { dialogState.onConfirm.invoke() },
поехал текст кнопки

2024-07-04 12:59 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/CreatingNoteIntroductionScreen.kt
> +            CustomTopBar(
![Screenshot_20240704_163040_care intouch app debug](https://github.com/INtouch-YP/intouch-android/assets/17237585/8fcbbb1b-2d7f-4517-be35-0b090dc4b089)

2024-07-04 13:00 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +        DiaryHeader(
![Screenshot_20240704_161725_care intouch app debug](https://github.com/INtouch-YP/intouch-android/assets/17237585/a718b0c7-7188-4bfb-8c9a-6ab1bcd143fc)

2024-07-04 13:00 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +                onConfirm = { dialogState.onConfirm.invoke() },
![Screenshot_20240704_161642_care intouch app debug](https://github.com/INtouch-YP/intouch-android/assets/17237585/797dbf3d-2654-4b41-92de-e06252559916)

2024-07-04 13:41 UTC, nim0y commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +
Done

2024-07-04 13:50 UTC, nim0y commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/CreatingNoteIntroductionScreen.kt
> +            CustomTopBar(
Не могу воспроизвести отсутствие текста кнопки , подскажи ттх  устройства?
Header  исправил.

2024-07-04 14:13 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/CreatingNoteIntroductionScreen.kt
> +            CustomTopBar(
Huawei mate 20 Android 10ый. На xiaomi redmi 2A показывает. Скорее всего кнопка не влезает в экран, поэтому он ее скукоживает. Если ты скорректируешь отступ сверху, то может все будет ок.

2024-07-04 14:21 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/CreatingNoteIntroductionScreen.kt
> +            CustomTopBar(
![Screenshot_20240704-181903](https://github.com/INtouch-YP/intouch-android/assets/17237585/d99cc3bf-a000-46aa-87a8-4d5060c9eb4c)

2024-07-04 14:22 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/CreatingNoteIntroductionScreen.kt
> +            CustomTopBar(
на нем тоже не по дизайну

2024-07-04 15:33 UTC, nim0y commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +                onConfirm = { dialogState.onConfirm.invoke() },
Похоже что исправил, посмотри пожалуйста . И Спасибо за ревью !

2024-07-04 19:35 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +    LoadingContainer(
LoadingContainer должен находится внутри DiaryNoteScreen, под тулбаром, чтобы на него можно было нажать

2024-07-04 19:35 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/diary/presentation/ui/DiaryNoteScreen.kt
> +            isLoading = true,
это лишнее

2024-07-05 08:24 UTC, smitford approved these changes

2024-07-08 05:58 UTC, DaniilKosmachev approved these changes

2024-07-09 05:47 UTC, merged