134 2.5 my diary emotion share
INtouch-YP/intouch-android pull request #164
Opened 2024-07-14 22:32 UTC by menta1

Работает сохранение дневника. 
Загрузка всех имеющихся записей дневников. 
Переключатель поделиться с врачом.
Удалить запись дневника

2024-07-16 09:42 UTC, smitford requested changes

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +    private val switchVisibleUC: SwitchVisibleUC,
я бы написал полностью UseCase, неочевидное сокращение

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                    id = event.idToShare
непонятно к чему относится id, к task, diary или может доктору

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                    id = event.idToDelete
аналогично

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                is Resource.Error -> {
добавить тост на то, что удаление не произошло, аналогично ниже

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                is Resource.Success -> {
для чтения лучше наверное отражать сначала ветку success, так как мы ожидаем, что этот кейс будет выполняться чаще. Плюс он информативно для нас важнее. Аналогично для схожих кейсов

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                }
сделать отдельную обработку ошибки при потери соединения с интернетом.

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +    private fun mapperToDiaryEntry(diary: Diary): DiaryEntry {
либо вынести в отдельный файл как маппер, лдибо перенести обработку в use case. Во вью моделе такого быть не должно

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +//        val entries = generateRandomDiaryEntries(count)
убрать

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
>      private fun generateRandomDiaryEntries(count: Int): List<DiaryEntry> {
это нужно еще?

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/data/EmotionsRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
suspend функция, тебе точно тут нужно запускать еще корутину? аналогичный вопрос к пунктам ниже.

2024-07-16 09:42 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/data/EmotionsRepositoryImpl.kt
> +    override suspend fun getDiaries(): Flow<Resource<List<Diary>, ErrorEntity>> = flow {
зачем флоу? у тебя же выше есть state flow

2024-07-16 09:58 UTC, smitford commented
проект не билдится 
![image](https://github.com/user-attachments/assets/e8da4e36-8a92-4918-9a4c-df6e085d2457)

2024-07-16 09:58 UTC, smitford commented
вижу кучу конфликтов, их надо решить

2024-07-16 20:36 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +    private val switchVisibleUC: SwitchVisibleUC,
Не мой код. Посмотри мои коммиты. Но этот код одобрили и он уже в dev

2024-07-16 20:38 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                    id = event.idToShare
Не мой код. Посмотри мои коммиты. Но этот код одобрили и он уже в dev

2024-07-16 20:38 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                    id = event.idToDelete
Не мой код. Посмотри мои коммиты. Но этот код одобрили и он уже в dev

2024-07-16 20:47 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                    id = event.idToDelete
если ты будешь работать над проектом и там будет код, который вызывает у тебя вопросы в плане оптимизации или читаемости, то ты будешь его править? В пуле это отображается как изменение сделанное тобой. Выше аналогично

2024-07-16 20:47 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                    id = event.idToDelete
не хочешь не правь

2024-07-16 21:01 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                    id = event.idToDelete
При чем тут это? Мне сказали что надо помочь, я спросил что нужно сделать. Мне конкретно сказали что делать. Я вижу что в коде есть не понятные мне вещи. Но не уверен что я один работает над этим.

2024-07-16 21:02 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +                is Resource.Success -> {
поправил

2024-07-16 21:10 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +    private fun mapperToDiaryEntry(diary: Diary): DiaryEntry {
Сделал. Но отдавать domain слою это точно не стоит

2024-07-16 21:22 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/data/EmotionsRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
Не мой код, но все же. Здесь конретно мы меняем контект выполнения в конктретном теле withContext, затем обратно возращаем дефолтный.

2024-07-16 22:28 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
> +//        val entries = generateRandomDiaryEntries(count)
убрал

2024-07-16 22:28 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/DiaryViewModel.kt
>      private fun generateRandomDiaryEntries(count: Int): List<DiaryEntry> {
убрал

2024-07-16 22:28 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/data/EmotionsRepositoryImpl.kt
> +    override suspend fun getDiaries(): Flow<Resource<List<Diary>, ErrorEntity>> = flow {
убрал

2024-07-17 06:50 UTC, smitford approved these changes

2024-07-17 08:47 UTC, DaniilKosmachev approved these changes

2024-07-17 08:47 UTC, DaniilKosmachev commented on app/src/main/java/care/intouch/app/feature/diary/data/modals/DiaryDTO.kt
> +    @SerialName("author")
Можно, думаю, не отмечать аннотацией поля, написание которых в API совпадает с общепринятым в kotlin

2024-07-17 18:09 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/data/modals/DiaryDTO.kt
> +    @SerialName("author")
Ну эти аннотации как то критически влияют на что то?))

2024-07-17 18:12 UTC, DaniilKosmachev commented on app/src/main/java/care/intouch/app/feature/diary/data/modals/DiaryDTO.kt
> +    @SerialName("author")
Вообще нет, просто меньше кода, визуально проще воспринимать))

2024-07-17 18:30 UTC, menta1 commented on app/src/main/java/care/intouch/app/feature/diary/data/modals/DiaryDTO.kt
> +    @SerialName("author")
Ну так модели которые работают с сетью лучше держать с полной  информацией. Может дашь мне замерджить?)

2024-07-17 19:04 UTC, merged