2.4 My Question - Data, Domain, Refactor presentation
INtouch-YP/intouch-android pull request #195
Opened 2024-07-17 22:04 UTC by DaniilKosmachev

На приветственном экране - данные все подгружаются с задания (пока id задания хардкод)
На экране вопросов, так же все подгружается с сервера (кроме картинки - она приходит как http), закомментил, поставил заглушку
Есть функционал поделиться с доктором
Для перевода задачи в статус - done (написана API)

2024-07-18 18:41 UTC, vladalexeco approved these changes

2024-07-18 19:40 UTC, smitford requested changes

2024-07-18 19:40 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/questions/data/converters/AssignmentsConvertor.kt
> +            //description = assignmentsBlock.description,
убрать

2024-07-18 19:40 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/questions/domain/models/TypeOfBlocks.kt
> +    UNDEFINED  // сделал на случай если новый тип добавят
комментарий убрать

2024-07-18 19:40 UTC, smitford commented on app/src/main/java/care/intouch/app/feature/questions/presentations/ui/questions/QuestionsViewModel.kt
> +    init {      // Получам данные по задаче
комментарии убрать везде

2024-07-19 05:16 UTC, Babaylov7 approved these changes

2024-07-19 07:24 UTC, smitford approved these changes

2024-07-19 08:27 UTC, merged