Feat: Added layout of bottom navigation bar and layout of top navigation bar
INtouch-YP/intouch-android pull request #26
Opened 2024-03-06 17:40 UTC by vladalexeco

2024-03-11 18:41 UTC, JudjinGM requested changes
Привет! Очень не хватает превью компоуза для всех элементов в файле NavElements.kt. Для передачи текста и изображений лучше использовать StringVO, ImageVO, так функции будут более гибкие к изменениям.

2024-03-11 18:41 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +    onClick: () -> Unit
Судя по новому дизайну, для данной кнопки надо передавать параметр enabled и в зависимости от этого установить логику выбора цвета (яркий или приглушенный зеленый)

2024-03-11 18:41 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +        modifier = Modifier.clickable { onClick.invoke() },
При нажатии на элемент происходит ripple и весь Box подсвечивается темным квадратом, что не очень красиво. Можно, как вариант, полностью eубрать рипл эффект, или добавить к modifier Box clip перед clickable вот так: 
modifier = Modifier.clip(RoundedCornerShape(12.dp)).clickable { onClick.invoke()
},

2024-03-11 18:41 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +fun NavBottomDefaultElement(
Наверное, можно объединить иконку и текст в один элемент через Column, а также добавить в функцию аргументы для логики выбора элемента и изменения цвета(сейчас outFocusTint не используется). 
Например, добавить аргумент id элемента, id выбранного элемента и сравнивая их выбирать или один цвет для иконки и текса или другой.
Также при нажатии на иконку также присутствует ripple эффект, его можно убрать вот так:
modifier.clickable(
                indication = null,
                interactionSource = remember { MutableInteractionSource() }) { onClick.invoke() }

2024-03-11 18:41 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +fun CustomBottomNavBar() {
Мне кажется, что в аргументах не хватает: 
   - firstItemText: StringVO,
   - secondItemText: StringVO,
   - thirdItemText: StringVO,
   -fourthItemText: StringVO,
        для текстов,
    - firstItemImage: ImageVO,
    - secondItemImage: ImageVO,
    - thirdItemImage: ImageVO,
    - fourthItemImage: ImageVO,
    для иконок
    - firstItemClick: () -> Unit,
    - secondItemClick: () -> Unit,
    - onPlusButtonClick: () -> Unit,
    - thirdItemClick: () -> Unit,
    - fourthItemClick: () -> Unit
    для кликов

2024-03-11 18:41 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +    ConstraintLayout(
сюда можно добавить 
val selectedIconIndex = rememberSaveable {
        mutableIntStateOf(0)
    }
а в клике элемента уже присваивать selectedIconIndex.intValue = id элемента. Тогда уже в элементе будет срабатывать логика изменения цвета в зависимости выбран сейчас элемент или нет

2024-03-11 18:41 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/UiKitSample.kt
> +fun NavigationSample() {
все превью лучше оборачивать в тему приложения

2024-03-11 18:41 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +                    .clickable { onBackArrowClick.invoke() },
Здесь также не нужный ripple эффект (при нажатии поверх стрелки появляется черный прозрачный квадрат).

2024-03-11 18:43 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +fun CustomTopBar(
Судя по дизайну есть варианты top bar без стрелки назад и без кнопки закрыть, возможно надо сделать дополнительные функции или возможно надо добавить в эту возможность кастомизации.

2024-03-11 18:55 UTC, vladalexeco commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +fun NavBottomDefaultElement(
Сделать иконку и текст одним элементом не получится, так как согласно макету отступ от края делается по иконке, а она значительно уже, чем текст.

2024-03-13 08:22 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +        Text(
Сюда имеет смысл добавить аргументы: 
maxLines = 1,
overflow = TextOverflow.Ellipsis,
иначе при длинных значениях все смотрится не очень. 
Мб еще добавить какие-то паддинги с обоих концов, тогда при длинных значениях текста, он не будет прям на краю элемента, это как сам решишь, мб и лишнее.

2024-03-13 08:22 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +    Box(
Здесь, наверное, надо использовать Row, так как если текст заголовка будет длинным, то он будет залазить на остальные элементы

2024-03-13 08:22 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +                style = InTouchTheme.typography.titleLargeTypography
Сюда тоже лучше поставить
maxLines = 1,
overflow = TextOverflow.Ellipsis,

2024-03-13 18:31 UTC, vladalexeco commented on app/src/main/java/care/intouch/app/UiKitSample.kt
> +fun NavigationSample() {
Оформил в виде отдельной функции preview, обернул в тему. Она находится сверху над этой.

2024-03-13 20:01 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +                .padding(top = 25.dp),
Сейчас текст заголовка не по центру, тк размер стрелки(24dp) и размер кнопки закрыть(47dp) разные, если установить .padding(top = 25.dp, start = 23.dp), то этот отступ закроет разницу и заголовок будет посерердине.

2024-03-13 20:12 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +            .height(98.dp)
Мне кажется, что здесь ошибка. Если посмотреть дизайн, но высота топбара "равна"(hug) высоте кнопки закрыть, а здесь, видимо, размер рамки в которой находиться данный компонент в дизайне. Я думаю, что надо здесь сделать также, выставлять высоту по наибольшему размеру элемента внутри.

2024-03-13 20:19 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +                modifier = Modifier.padding(end = 24.dp, top = 20.dp)
Здесь тоже надо будет поправить padding end, padding top, получается, будет не нужен.

2024-03-14 09:48 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +        Text(
Сейчас цвет текста в превью черный, по макету -темно синий, можно добавить color = InTouchTheme.colors.textColorBlue и это исправит несоответствие

2024-03-14 09:48 UTC, JudjinGM approved these changes

2024-03-14 16:37 UTC, avanisimov commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +@Composable
Можно разделить этот файл на 2: TopBar и BottomBar - будет проще ориентироваться в коде, сейчас тут 400 строк - это много

2024-03-14 16:37 UTC, avanisimov commented on uikit/src/main/java/care/intouch/uikit/ui/navigation/NavElements.kt
> +        }
можно сделать стейт через делегат 
    var selectedElementId: ElementId by rememberSaveable {
            mutableStateOf(ElementId.HOME_ID)
        }
        
и тогда уже пользоваться енумом вместо инта 
selectedElementId = ElementId.HOME_ID

2024-03-20 10:32 UTC, avanisimov approved these changes

2024-03-20 10:32 UTC, merged