Feature/11 UI kit buttons
INtouch-YP/intouch-android pull request #33
Opened 2024-03-20 12:14 UTC by Keiyakushi

2024-03-22 09:03 UTC, JudjinGM requested changes

2024-03-22 09:03 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/ui/buttons/PrimaryButton.kt
> +    onClick: () -> Unit,
Мне кажеться, что не хватает такие параметры как: 
1) modifier - чтобы можно было пееропределить падинги, ширину, высоту при необходимости
2) text - для того чтобы передать текст в кнопке
3) IsEnabled - чтобы можно было менять его состояние enable/disable
4) isHasStroke - есть ли у кнопки обводка границы
5) enableBackgroundColor и enableTextColor - так можно задать задний цвет кнопки и текст, когда он enable
6) disableBackgroundColor и disableTextColor - так можно задать задний цвет кнопки и текст, когда он disable
7) borderStrokeColor - так можно передать цвет обводки границы
8) textStyle - так можно передать стиль текста (размер итд)
Лучше всего, чтобы часть этих параметров имели дефолтные значения, что будет удобно для того чтобы использовать кнопку прямо из коробки.

2024-03-22 09:03 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/ui/buttons/PrimaryButton.kt
> +    Button(
Здесь можно попробовать не подстраиваться к Material design кнопке, а сделать свою реализацию с Row итд

2024-03-22 09:03 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/ui/buttons/PrimaryButton.kt
> +        Text(text = "Call to action", style = InTouchTheme.typography.titleMediumTypography)
сбюда надо передавать текст, стиль и цвет (в зависимоти от состояния кнопки) из аргумента функции.

2024-03-22 09:03 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/ui/buttons/PrimaryButton.kt
> +        }, onClick = { onClick.invoke() }
Здесь можно поставить условие, чтобы при isEnabled = false был, например, пустой { }, так кнопка будет отключена

2024-03-22 09:03 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/ui/buttons/PrimaryButton.kt
> +        colors = when (mode) {
по сути этот mode не нужен, все разрулиться через параметры переданные в аргументы функции

2024-03-22 09:03 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/ui/buttons/PrimaryButton.kt
> +        border = if (mode == ButtonModeEnum.ABLESTROKE) {
вот здесь можно проверять isHasStroke

2024-03-27 12:35 UTC, JudjinGM submitted a review, later dismissed

2024-04-03 04:56 UTC, ImNia approved these changes
Мне кажется стоит перенести верстку в модуль UIKit, сейчас она в app лежит

2024-04-03 09:07 UTC, JudjinGM commented
Не забудь, пожалуйста, добавить кнопки в Samples

2024-04-03 14:52 UTC, JudjinGM approved these changes

2024-04-03 15:30 UTC, merged