Add SecondaryButtons and IconicButtons.
INtouch-YP/intouch-android pull request #41
Opened 2024-04-02 21:04 UTC by Keiyakushi

2024-04-03 08:59 UTC, JudjinGM requested changes
Я в дизайне не нашел, где иконки-кнопки используются отдельно. Иконка с пером в круге, мне кажеться, это иконка приложения, TapBarPlus заложена уже в наигации и ее сделал Владимир, тоже самое и с кнопкой закрыть - она реализована в рамках задачи Владимира. Думаю, что IconicButtons отдельно не нужны.

2024-04-03 08:59 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/SecondaryButtons.kt
> +        enableBackgroundColor = InTouchTheme.colors.input,
Мне кажется, что здесь надо добавить новый сolor - transparent(прозрачный) и использовать его для заднего фона. Добавить его можно вот так: в theme/Color.kt в data class InTouchColors надо добавить поле val transparent: Color = Color.Transparent

2024-04-03 08:59 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/SecondaryButtons.kt
> +        enableBackgroundColor = InTouchTheme.colors.input,
Здесь тоже самое с прозрачным фоном

2024-04-03 08:59 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/SecondaryButtons.kt
> +fun PrimaryButtonDarkPreview() {
тут опечатка, SecondaryButtonDarkPreview

2024-04-03 08:59 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/SecondaryButtons.kt
> +fun PrimaryButtonWhitePreview() {
тут опечатка, SecondaryButtonWhitePreview

2024-04-03 09:07 UTC, JudjinGM commented
Также, не забудь, пожалуйста, добавить сделанные кнопки в Samples

2024-04-08 04:59 UTC, ImNia approved these changes

2024-04-14 10:19 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/DeleteButtons.kt
> +        disableTextColor = InTouchTheme.colors.input
Кнопки не соответсвуют дизайну, сейчас падинги для текста берутся из IntouchButton. 
Добавь contentPadding= PaddingValues (horizontal = 51.5.dp, vertical = 11.5.dp) и для кнопки DeleteButtonDefault и для кнопки DeleteButtonActive

2024-04-14 10:27 UTC, JudjinGM requested changes

2024-04-14 10:27 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/TertiaryButtons.kt
> +    contentPadding: PaddingValues = PaddingValues(horizontal = 10.dp, vertical = 10.dp),
Падинги не соответсвуют дизайну 
![image](https://github.com/INtouch-YP/intouch-android/assets/102486283/cdd58598-e049-488d-a838-05f2f8ce0a17)

2024-04-14 10:27 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/TertiaryButtons.kt
> +fun TertiaryButtonDefault() {
не хватает слово Preview

2024-04-14 10:27 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/TertiaryButtons.kt
> +fun TertiaryButtonActive() {
не хватает слово Preview

2024-04-14 10:30 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/buttons/DeleteButtons.kt
> +fun DeleteButtonActive(
выглядит так, что это два разных состояния кнопки, default и active, которые отличаются цветами, добавь isActive = false и изменение цвета в зависимоcти от этого состояние. Тоже самое и для TertiaryButtons

2024-04-15 11:51 UTC, JudjinGM approved these changes

2024-04-15 11:54 UTC, merged