UIKit Checkbox
INtouch-YP/intouch-android pull request #42
Opened 2024-04-03 04:50 UTC by ImNia

2024-04-03 09:40 UTC, JudjinGM requested changes

2024-04-03 09:40 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +            .padding(
Если задавать падинги сверху, то они будут сумироваться с этими, так что предлагаю убрать падинги во внутрь Box

2024-04-03 09:40 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +            modifier = modifier
При передачи modifier сверху, он будет иметь в себе уже все установленные параметы. Здесь Лучше установить modifier = Modifier

2024-04-03 09:40 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +                .size(24.dp)
сюда можно добавить падинги которые указаны в дизайне (начальный, верхний и нижний)

2024-04-03 09:40 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +                    modifier = modifier
Тут также лучше установть modifier = Modifier

2024-04-03 09:40 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +                .padding(horizontal = 12.dp),
Здесь также modifier = Modifier, а также начальный padding должен быть равен 12 dp, а конечный 2 dp.

2024-04-03 09:40 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +    onClick: () -> Unit
Предлагаю сюда вынести установку стиля текста с дефолтным значением

2024-04-03 09:40 UTC, JudjinGM commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +            style = InTouchTheme.typography.bodyBold,
стиль текста по дизайну InTouchTheme.typography.bodyRegular

2024-04-03 11:29 UTC, ImNia commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +    onClick: () -> Unit
Сделала

2024-04-03 11:29 UTC, ImNia commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +            style = InTouchTheme.typography.bodyBold,
Поправила

2024-04-03 11:30 UTC, ImNia commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +                .padding(horizontal = 12.dp),
Поправила

2024-04-03 11:30 UTC, ImNia commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +                    modifier = modifier
Поправила

2024-04-03 11:30 UTC, ImNia commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +                .size(24.dp)
Сделала

2024-04-03 11:30 UTC, ImNia commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +            modifier = modifier
Поправила

2024-04-03 11:30 UTC, ImNia commented on uikit/src/main/java/care/intouch/uikit/ui/Checkbox.kt
> +            .padding(
Поправила

2024-04-03 12:11 UTC, JudjinGM approved these changes

2024-04-10 19:02 UTC, vladalexeco approved these changes

2024-04-11 09:14 UTC, merged