1.2 Authentication
INtouch-YP/intouch-android pull request #94
Opened 2024-06-14 13:34 UTC by Keiyakushi

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/domain/useCase/GetTokenAuthentication.kt
> +    suspend operator fun invoke(username: String, password: String): Resource<String, ErrorEntity>
Предлагаю переименовать use сase. В данном случае происходит вход в приложение используя email/password. Следовательно, название должно быть что-то типа LoginByEmailUseCase. Также не забывай писать в названии UseCase

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/domain/useCase/GetTokenAuthentication.kt
> +                    when (val result2 = userRepository.getUser()) {
не используй в названии цифры типа result2, result3 итд, надо переименовать

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/domain/useCase/GetTokenAuthentication.kt
> +                        is Resource.Error -> {
надо обработать ошибку

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/domain/useCase/GetTokenAuthentication.kt
> +            token: String,
password?

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/domain/useCase/GetTokenAuthentication.kt
> +        ): Resource<String, ErrorEntity> {
просто предложение, можно оставить как есть: тут можно вернуть Boolean  и тогда при success будет true

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +    var passwordText by remember { mutableStateOf("") }
Эти все поля должны быть во вьюмодели

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +const val emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\$"
перенести во вьюмодель

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +internal fun isValidPassword(password: String): Boolean {
перенести во вьюмодель

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
>  fun AuthenticationScreenPreview() {
У меня не работает превью, у тебя все норм?

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            caption = if (isErrorLogin == isValidEmail(loginText)) {
логика вьюмодели

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            error = isErrorLogin == isValidEmail(loginText),
логика вьюмодели

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            isEnabled = !loginText.isNullOrEmpty() and !passwordText.isNullOrEmpty(),
логика вьюмодели

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            text = "LOGIN",
в ресурсы

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            text = "Forgot password?",
в ресурсы

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            hint = StringVO.Plain("Password"),
весь захардкоженный текст должен быть в ресурсах

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +                StringVO.Plain("Incorrect. Please try again")
в ресурсы

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            text = "Sign in to continue",
в ресурсы

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            text = "Welcome to INtouch!",
в ресурсы

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +    return if (email == "") {
isBlank()

2024-06-16 09:20 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +    if (password == "") return true
isBlank()

2024-06-16 09:24 UTC, JudjinGM reviewed
Надо отрефакторить AuthenticationScreen- вынести всю валидацию как минимум во вьюмодель. Сейчас ui перегружен логикой вьюмодели, а вьюмодель по сути пустая.

2024-06-16 09:27 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            error = isErrorPassword == isValidPassword(passwordText),
логика вьюмодели

2024-06-16 09:27 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            caption = if (isErrorPassword == isValidPassword(passwordText)) {
логика вьюмодели

2024-06-20 13:13 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +                .padding(top = 326.dp, start = 28.dp, end = 28.dp),
Размеры должны быть кратные 4

2024-06-20 13:13 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +                .padding(bottom = 85.dp, start = 69.5.dp, end = 69.5.dp),
Размеры должны быть кратные 4

2024-06-20 13:13 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            onValueChange = { viewModel.savePassword(it) },
Здесь и далее, сделай, пожалуйста все взаимодействие с вьюмоделью через один публичный метод onEvent

2024-06-27 06:31 UTC, Babaylov7 commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +private fun AuthenticationScreen(
![1](https://github.com/INtouch-YP/intouch-android/assets/130746178/4dd6778a-1fbb-4d28-bb8e-39d0bf4ee53f)
Ты все вьюхи обернул в Box, оберни их в Column (за исключением head_background_small, его я оставил в Box, а все остальные через Column поместил поверх)  и вместо отступов ставь Spacer(modifier = Modifier.height(**.dp)) (чтоб положение выровнять)  
Через Column  ты все вьюхи друг под другом разместишь и они накладываться друг на друга не будут при маленьком экране

2024-06-27 06:31 UTC, Babaylov7 commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            text = stringResource(care.intouch.app.R.string.welcome_to_intouch),
Текст оборачиваем в StringVO
text = StringVO.Resource(resId = care.intouch.app.R.string.profile_title).value()

2024-06-27 06:31 UTC, Babaylov7 commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            hint = StringVO.Plain(stringResource(care.intouch.app.R.string.e_mail)),
Используй тут StringVO.Resource(resId = care.intouch.app.R.string.profile_title) 
В StringVO передача id ресурса предусмотрена

2024-06-27 15:50 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            text = stringResource(care.intouch.app.R.string.welcome_to_intouch),
Мне кажется, что имеет смысл оборачивать текст только тот, что приходит из вьюмодели, а здесь не имеет смысла, думаю, что можно оставить как есть

2024-06-29 10:25 UTC, JudjinGM requested changes

2024-06-29 10:25 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +        Icon(
Почему здесь Icon, а не Image?

2024-06-29 10:25 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +            modifier = Modifier.fillMaxSize()
мне кажется, не хватает horizontalAlignment = Alignment.CenterHorizontally и тогда не надо будет прописывать у каждого элемента как располагатся

2024-06-29 10:27 UTC, JudjinGM reviewed
Верстка не соответвует дизайну-растяни текстфилды на ширину, установи паддинги по краям согласно дизайну, проверь все паддинги между элементами, также сделай их кратными 4.

2024-06-29 10:36 UTC, JudjinGM requested changes

2024-06-29 10:36 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/AuthenticationScreen.kt
> +                onValueChange =
Почему тут сразу 3 ивента? у тебя же происходит только один ивент. Вызывай по нему во вьюмодели нужные методы. Тоже самое и ниже

2024-06-29 10:36 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/viewModel/AuthViewModel.kt
> +                    passwordCaption = StringVO.Plain("Incorrect. Please try again")
в ресурсы

2024-06-29 10:36 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/viewModel/AuthViewModel.kt
> +                    loginCaption = StringVO.Plain("Not a valid e-mail address")
в ресурсы

2024-06-29 10:36 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/viewModel/AuthViewModel.kt
> +                loginByEmail(event.username, event.password)
А почему ивент используеться для хранения данных? Доставай из стейта что тебе нужно

2024-06-29 10:36 UTC, JudjinGM commented on app/src/main/java/care/intouch/app/feature/authorization/presentation/ui/models/AuthenticationDataEvent.kt
> +    data class OnLoginButtonClicked(val username: String, val password: String) :
Здесь надо удалить эти данные из ивента, нажатие кнопки тебе по сути отдает факт нажатия.

2024-07-01 07:02 UTC, JudjinGM submitted a review, later dismissed

2024-07-01 07:22 UTC, DaniilKosmachev approved these changes

2024-07-01 11:19 UTC, Babaylov7 approved these changes

2024-07-03 09:31 UTC, merged